sudo: required
dist: trusty

language: node_js

if: tag IS present

before_install:
  - cd webapp

matrix:
  include:
    - os: linux

node_js:
  - 8

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run dist
