language: node_js
# no change
#if: tag IS present

#before_install:
#  - cd webapp

matrix:
  include:
    - os: windows

node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run dist
