sudo: required
dist: trusty

language: node_js

#if: tag IS present

before_install:
  - cd webapp

matrix:
  include:
    - os: windows

node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run dist
